{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "registryindexer.fullname" . }}
  labels:
    {{- include "registryindexer.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "registryindexer.selectorLabels" . | nindent 6 }}
{{- end }}
